# Generated by Django 5.2.6 on 2025-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
