# Generated by Django 5.1.6 on 2025-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_category_artikle_catg'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
