# Generated by Django 5.1.6 on 2025-09-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_artikle_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikle',
            options={'ordering': ('-views',)},
        ),
        migrations.AddField(
            model_name='artikle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
