# Generated by Django 5.1.6 on 2025-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_artikle_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikle',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
