# Generated by Django 5.2.7 on 2025-10-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='birth_year',
            field=models.CharField(default='1400', max_length=4, verbose_name='سال تولد'),
        ),
    ]
