# Generated by Django 5.2.6 on 2025-10-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_contactmessage_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='birth_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
