# Generated by Django 5.2.7 on 2025-10-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_contactmessage_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='birth_year',
        ),
    ]
