# Generated by Django 5.2.7 on 2025-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_remove_contactmessage_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='birth_year',
            field=models.CharField(default='1400', max_length=4, verbose_name='سال تولد'),
        ),
    ]
