# Generated by Django 5.2.7 on 2025-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_contactmessage_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
