# Generated by Django 5.1.6 on 2025-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='birth_year',
            field=models.CharField(default='1400', max_length=4, verbose_name='سال تولد'),
        ),
        migrations.AddField(
            model_name='message',
            name='intro_method',
            field=models.CharField(choices=[('search', 'از طریق جست و جو در اینترنت'), ('friend', 'از طریق دوستان')], default='serach', max_length=10, verbose_name='نحوه آشنایی با سایت'),
        ),
    ]
