# Generated by Django 5.2.7 on 2025-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_contactmessage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='education_level',
            field=models.CharField(choices=[('primary', 'ابتدایی'), ('secondary', 'راهنمایی'), ('highschool', 'دبیرستان'), ('diploma', 'دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا')], default='diploma', max_length=20, verbose_name='میزان سواد'),
        ),
    ]
