# Generated by Django 5.1.6 on 2025-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_message_birth_year_message_intro_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='message',
            name='intro_method',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
