# Generated by Django 5.2.4 on 2025-10-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_contact_birth_year_alter_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='intro_method',
            field=models.CharField(default='search', max_length=10, verbose_name='How to get to know the site'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birth_year',
            field=models.CharField(blank=True, default='1400', max_length=4, null=True, verbose_name='year of birth'),
        ),
    ]
