# Generated by Django 5.2.7 on 2025-10-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_contactmessage_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='education_level',
        ),
    ]
