# Generated by Django 5.1.6 on 2025-10-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_message_birth_year_message_intro_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='message',
            name='intro_method',
        ),
    ]
