# Generated by Django 5.2.7 on 2025-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_remove_contactmessage_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='intro_method',
            field=models.CharField(choices=[('search', 'از طریق جستجو در اینترنت'), ('friend', 'معرفی دوستان')], default='search', max_length=10, verbose_name='نحوه آشنایی با سایت'),
        ),
    ]
