# Generated by Django 5.1.6 on 2025-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_remove_message_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='birth_year',
            field=models.CharField(blank=True, default='1400', max_length=4, verbose_name='سال تولد'),
        ),
        migrations.AddField(
            model_name='message',
            name='intro_method',
            field=models.CharField(blank=True, choices=[('search', 'از طریق جست و جو در اینترنت'), ('friend', 'از طریق دوستان')], default='serach', max_length=10, verbose_name='نحوه آشنایی با سایت'),
        ),
    ]
