# Generated by Django 5.1.6 on 2025-10-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_message_birth_year_message_intro_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='name',
        ),
    ]
