# Generated by Django 5.1.6 on 2025-10-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_rename_title_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='title',
        ),
    ]
