# Generated by Django 5.1.6 on 2025-10-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_rename_name_message_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='name',
        ),
    ]
