# Generated by Django 5.1.6 on 2025-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_message_birth_year_alter_message_intro_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='birth_year',
            field=models.CharField(blank=True, default='1400', max_length=4, null=True, verbose_name='سال تولد'),
        ),
    ]
