# Generated by Django 5.1.6 on 2025-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_message_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='intro_method',
            field=models.CharField(blank=True, choices=[('search', 'از طریق جست و جو در اینترنت'), ('friend', 'از طریق دوستان')], default='serach', max_length=10, null=True, verbose_name='نحوه آشنایی با سایت'),
        ),
    ]
